drop table IMCUSR.SMETA_MAP_COL;

CREATE TABLE IMCUSR.SMETA_MAP_COL
(
COL_MAP_ID                    VARCHAR2(20)   NOT NULL,
MAP_SEQ                       NUMBER(10)    NOT NULL,
TOBE_OWN_NAME                 VARCHAR2(100),
TOBE_TBL_NAME                 VARCHAR2(20)   NOT NULL,
TOBE_TBL_KOR_NAME             VARCHAR2(200) ,
TOBE_COL_NAME                 VARCHAR2(100) ,
TOBE_COL_KOR_NAME             VARCHAR2(10)  ,
TOBE_COL_DAT_TP_NAME          VARCHAR2(10)  ,
TOBE_COL_DAT_LEN              VARCHAR2(10)  ,
TOBE_COL_DAT_DCML_LEN         VARCHAR2(10)  ,
TOBE_COL_PK_YN_NAME           VARCHAR2(10)  ,
ASIS_OWN_NAME                 VARCHAR2(100) ,
ASIS_TBL_NAME                 VARCHAR2(20)  ,
ASIS_TBL_KOR_NAME             VARCHAR2(200) ,
ASIS_COL_NAME                 VARCHAR2(100) ,
ASIS_COL_KOR_NAME             VARCHAR2(10)  ,
ASIS_COL_DAT_TP_NAME          VARCHAR2(10)  ,
ASIS_COL_DAT_LEN              VARCHAR2(10)  ,
ASIS_COL_DAT_DCML_LEN         VARCHAR2(10)  ,
ASIS_COL_PK_YN_NAME           VARCHAR2(10)  ,
DTLT_VAL                      VARCHAR2(500) ,
MIG_RULE_CN                   VARCHAR2(1000),
LAST_MOD_DT_NAME              VARCHAR2(50)  ,
CHRGR1_NAME                   VARCHAR2(200) ,
CHRGR2_NAME                   VARCHAR2(200) ,
CHRGR3_NAME                   VARCHAR2(200) 
)
TABLESPACE SYSTEM
NOCOMPRESS;
ALTER TABLE SMETA_MAP_COL
ADD PRIMARY KEY(COL_MAP_ID,MAP_SEQ,TOBE_TBL_NAME );
GRANT SELECT, INSERT, UPDATE, DELETE ON SMETA_MAP_COL TO IMCUSR;



drop table IMCUSR.SMETA_MAP_CODE;

CREATE TABLE IMCUSR.SMETA_MAP_CODE
(
CODE_MAP_ID                   VARCHAR2(20)   NOT NULL,
DOM_NAME                      VARCHAR2(200),
APP_GRP_NAME                  VARCHAR2(200),
APP_NAME                      VARCHAR2(100),
TOBE_CODE_DOM_ENG_NAME        VARCHAR2(100)   NOT NULL,
TOBE_CODE_DOM_KOR_NAME        VARCHAR2(200) ,
TOBE_VALID_CODE_VAL           VARCHAR2(100)  NOT NULL,
TOBE_VALID_CODE_NAME          VARCHAR2(1000)  ,
ASIS_CODE_NAME                VARCHAR2(200) ,
ASIS_VALID_CODE_VAL           VARCHAR2(100) ,
ASIS_VALID_CODE_NAME          VARCHAR2(1000)  ,
SPCMNT_MATTER_CN              VARCHAR2(4000),
LAST_MOD_DT_NAME              VARCHAR2(50)  ,
CHRGR1_NAME                   VARCHAR2(200) ,
CHRGR2_NAME                   VARCHAR2(200) ,
CHRGR3_NAME                   VARCHAR2(200) ,
CHRGR4_NAME                   VARCHAR2(200) ,
REGR_IP                       VARCHAR2(50)  ,
REQ_NO                        VARCHAR2(50)  ,
REGR_ID                       VARCHAR2(50)  ,
USR_NAME                      VARCHAR2(100) 
)
TABLESPACE SYSTEM
NOCOMPRESS;
ALTER TABLE SMETA_MAP_CODE
ADD PRIMARY KEY(CODE_MAP_ID,TOBE_CODE_DOM_ENG_NAME,TOBE_VALID_CODE_VAL );
GRANT SELECT, INSERT, UPDATE, DELETE ON SMETA_MAP_CODE TO IMCUSR;
